// @ts-nocheck
/**
 * Engezna Merchant Database Setup Script
 * =======================================
 * Sets up the "Engezna Merchants Database" Google Sheet with:
 * - 5 category sheets + 3 management sheets
 * - Arabic headers and structure
 * - Real merchant data from Beni Suef, Egypt
 * - Priority classification and wave assignment
 * - Dashboard with counts and targets
 *
 * Usage:
 *   npx tsx scripts/merchant-database-setup.ts
 *
 * Prerequisites:
 *   - Service account JSON key file at ./credentials/service-account.json
 *     OR set GOOGLE_SERVICE_ACCOUNT_KEY env var with the JSON content
 *   - The Google Sheet must be shared with the service account email
 */

import { google, sheets_v4 } from 'googleapis';
import { JWT } from 'google-auth-library';
import * as fs from 'fs';
import * as path from 'path';

// ============================================================
// CONFIGURATION
// ============================================================

const SPREADSHEET_ID = '1q4nndS9UFRP3dSaZZj9bpLonNghtw-hcYcag4F5c00c';

const CATEGORY_SHEETS = [
  { title: '🍔 مطاعم', emoji: '🍔', category: 'مطاعم' },
  { title: '💊 صيدليات', emoji: '💊', category: 'صيدليات' },
  { title: '🛒 سوبر ماركت', emoji: '🛒', category: 'سوبر ماركت' },
  { title: '🍰 حلويات وكافيهات', emoji: '🍰', category: 'حلويات وكافيهات' },
  { title: '🥬 خضار وفواكه', emoji: '🥬', category: 'خضار وفواكه' },
];

const MANAGEMENT_SHEETS = ['📊 لوحة التحكم', '📈 متابعة الأداء', '📊 CRM'];

const HEADERS = [
  '#',
  'اسم المتجر',
  'النوع الفرعي',
  'العنوان',
  'المنطقة',
  'رقم الهاتف 1',
  'رقم الهاتف 2',
  'فيسبوك',
  'انستجرام',
  'جوجل ماب',
  'التقييم ⭐',
  'عدد التقييمات',
  'ساعات العمل',
  'لديه توصيل؟',
  'حالة المتجر',
  'أولوية الاستقطاب',
  'الموجة المستهدفة',
  'حالة التواصل',
  'المندوب المسؤول',
  'نتيجة التواصل',
  'تاريخ التواصل',
  'تاريخ المتابعة',
  'تم التسجيل؟',
  'ملاحظات',
  'تاريخ آخر تحديث',
];

// ============================================================
// MERCHANT DATA - Beni Suef, Egypt
// ============================================================

interface MerchantData {
  name: string;
  subtype: string;
  address: string;
  area: string;
  phone1: string;
  phone2: string;
  facebook: string;
  instagram: string;
  googleMaps: string;
  rating: number;
  reviewCount: number;
  hours: string;
  hasDelivery: string;
  status: string;
}

function classifyPriority(rating: number, reviewCount: number): { priority: string; wave: string } {
  if (rating >= 4.0 && reviewCount >= 20) {
    return { priority: 'أولوية عالية', wave: 'موجة 1' };
  }
  if (rating >= 3.5 || reviewCount >= 10) {
    return { priority: 'أولوية متوسطة', wave: 'موجة 2' };
  }
  return { priority: 'أولوية منخفضة', wave: 'موجة 3' };
}

const today = new Date().toISOString().split('T')[0];

// --- RESTAURANTS ---
const restaurants: MerchantData[] = [
  {
    name: 'مطعم أوزي للمشويات',
    subtype: 'مشويات',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '01200604020',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Oozy+Restaurant+Beni+Suef',
    rating: 4.3,
    reviewCount: 85,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم بوليفار',
    subtype: 'عالمي / تركي',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '01148484827',
    phone2: '01200604020',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Bolivar+Restaurant+Beni+Suef',
    rating: 4.2,
    reviewCount: 120,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'نايل بلازا',
    subtype: 'مصري / عالمي',
    address: 'كورنيش النيل، حي الزهور، بني سويف',
    area: 'كورنيش النيل',
    phone1: '01151150023',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Plaza+Beni+Suef',
    rating: 4.1,
    reviewCount: 95,
    hours: '12:00 م - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم كافيلو',
    subtype: 'إيطالي / فاين داينينج',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '0822122277',
    phone2: '0822122295',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Cavello+Restaurant+Beni+Suef',
    rating: 4.4,
    reviewCount: 65,
    hours: '01:00 م - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم إيفينتو',
    subtype: 'إيطالي',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '0822214640',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Evento+Restaurant+Beni+Suef',
    rating: 4.3,
    reviewCount: 55,
    hours: '12:00 م - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم كافيار',
    subtype: 'مأكولات بحرية',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '0822280229',
    phone2: '01025515255',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Caviar+Restaurant+Beni+Suef',
    rating: 4.2,
    reviewCount: 78,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'لاميرا',
    subtype: 'ياباني / فاست فود',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '01226933339',
    phone2: '01018882560',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Lamera+Restaurant+Beni+Suef',
    rating: 4.0,
    reviewCount: 42,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'بكار كريب',
    subtype: 'كريب / فاست فود',
    address: 'ميدان الزراعيين، بني سويف',
    area: 'وسط البلد',
    phone1: '0822311611',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Bakkar+Crepe+Beni+Suef',
    rating: 4.0,
    reviewCount: 35,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم علي بابا',
    subtype: 'مشويات / فاست فود',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '01224407144',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ali+Baba+Restaurant+Beni+Suef',
    rating: 4.1,
    reviewCount: 48,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سيدي عبد الرحمن',
    subtype: 'شرقي / مصري',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Sidi+Abdelrahman+Restaurant+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '12:00 م - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'LA VIE BOAT',
    subtype: 'مصري / نيلي',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=La+Vie+Boat+Beni+Suef',
    rating: 4.3,
    reviewCount: 58,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'نيو كوب مارينا كافيه',
    subtype: 'مصري / كافيه',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=New+Cop+Marina+Beni+Suef',
    rating: 4.0,
    reviewCount: 25,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كشري البكري',
    subtype: 'كشري',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '0822353613',
    phone2: '01223470078',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Koshari+Al+Bakry+Beni+Suef',
    rating: 4.5,
    reviewCount: 150,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مكرونة البكري',
    subtype: 'مكرونة / حلويات',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Macarona+El+Bakry+Beni+Suef',
    rating: 4.0,
    reviewCount: 22,
    hours: '10:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'الشريف مشويات',
    subtype: 'مشويات',
    address: 'شارع عبد السلام عارف، أمام السجل المدني، بني سويف',
    area: 'وسط البلد',
    phone1: '01029884025',
    phone2: '01212429908',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Sherif+Grill+Beni+Suef',
    rating: 4.2,
    reviewCount: 90,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'الواحة',
    subtype: 'مصري / مشويات',
    address: 'شرق النيل، بجوار التوحيد والنور، خلف الجامع الكبير',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Waha+Restaurant+Beni+Suef',
    rating: 4.0,
    reviewCount: 35,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كريب الخديوي',
    subtype: 'كريب / فاست فود',
    address: 'بجوار المسجد الكبير، بجانب المحافظة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Crepe+El+Khedive+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم تيوليب إن',
    subtype: 'فندقي / عالمي',
    address: 'شارع أحمد عرابي، داخل فندق تيوليب إن، بني سويف',
    area: 'وسط البلد',
    phone1: '0822366993',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Tulip+Inn+Beni+Suef',
    rating: 3.9,
    reviewCount: 40,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'وادي السلطان',
    subtype: 'مصري / شرقي',
    address: 'بني سويف الجديدة، شرق النيل، أمام كلية تعليم صناعي',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Wadi+Sultan+Beni+Suef',
    rating: 4.1,
    reviewCount: 28,
    hours: '12:00 م - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'زاكس فرايد تشكن',
    subtype: 'دجاج مقلي / فاست فود',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Zacks+Fried+Chicken+Beni+Suef',
    rating: 3.9,
    reviewCount: 32,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'جلوبال ريستورانت',
    subtype: 'عالمي',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Global+Restaurant+Beni+Suef',
    rating: 3.8,
    reviewCount: 22,
    hours: '12:00 م - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كازا ميزا',
    subtype: 'فاست فود / وجبات سريعة',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kaza+Meza+Beni+Suef',
    rating: 3.7,
    reviewCount: 15,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'جراج لاونج',
    subtype: 'كافيه / مطعم',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Garage+Lounge+Beni+Suef',
    rating: 4.0,
    reviewCount: 18,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سيليا ريستورانت',
    subtype: 'مصري / عصري',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Celia+Restaurant+Beni+Suef',
    rating: 4.1,
    reviewCount: 25,
    hours: '12:00 م - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'تروبيكانا فود',
    subtype: 'فاست فود',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Tropicana+Food+Beni+Suef',
    rating: 3.8,
    reviewCount: 20,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كشري المنشاوي',
    subtype: 'كشري',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Koshari+Menshawi+Beni+Suef',
    rating: 4.3,
    reviewCount: 110,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم ع الفحم',
    subtype: 'مشويات',
    address: 'مول الشروق، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=3al+Fa7m+Beni+Suef',
    rating: 4.0,
    reviewCount: 45,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فريندز',
    subtype: 'كريب / بيتزا',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Friends+Restaurant+Beni+Suef',
    rating: 3.9,
    reviewCount: 28,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كارفور',
    subtype: 'فاست فود / مصري',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Carfore+Restaurant+Beni+Suef',
    rating: 3.6,
    reviewCount: 12,
    hours: '10:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم الأباصيري',
    subtype: 'مصري / بيتزا',
    address: 'شارع الأباصيري متفرع من شارع عبد السلام عارف',
    area: 'وسط البلد',
    phone1: '0822214611',
    phone2: '01221283566',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Abasiry+Beni+Suef',
    rating: 4.0,
    reviewCount: 38,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  // === NEW RESTAURANTS (31-60) ===
  {
    name: 'مطعم وكافيه القبطان',
    subtype: 'مصري / مشويات',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '01067944480',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Captain+Restaurant+Beni+Suef',
    rating: 4.2,
    reviewCount: 65,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم أكلات عالمية',
    subtype: 'مصري / عالمي',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '01061541545',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Aklat+Alamia+Kornish+Beni+Suef',
    rating: 4.0,
    reviewCount: 42,
    hours: '12:00 م - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم أكلات سورية',
    subtype: 'سوري',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '01017124700',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Syrian+Food+Beni+Suef',
    rating: 4.1,
    reviewCount: 35,
    hours: '11:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'منتون كافيه ومطعم',
    subtype: 'كافيه / مطعم',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Menton+Cafe+Restaurant+Beni+Suef',
    rating: 4.0,
    reviewCount: 28,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'قرية السلطان',
    subtype: 'مصري / شرقي',
    address: 'بني سويف الجديدة، شرق النيل، أمام كلية تعليم صناعي',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Sultan+Village+Beni+Suef',
    rating: 4.3,
    reviewCount: 75,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'هوى الشام',
    subtype: 'سوري / شاورما',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '01068501571',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Hawa+El+Sham+Beni+Suef',
    rating: 4.2,
    reviewCount: 55,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كنتاكي (KFC)',
    subtype: 'دجاج مقلي / سلسلة عالمية',
    address: 'أرض الحرية، بجوار التوحيد والنور، بني سويف',
    area: 'أرض الحرية',
    phone1: '19019',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=KFC+Beni+Suef',
    rating: 4.0,
    reviewCount: 250,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كوك دور',
    subtype: 'دجاج / فاست فود',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '19935',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Cook+Door+Beni+Suef',
    rating: 4.1,
    reviewCount: 180,
    hours: '11:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم الطيب',
    subtype: 'مصري / فول وطعمية',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Tayeb+Restaurant+Beni+Suef',
    rating: 3.9,
    reviewCount: 30,
    hours: '06:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'حاتي الشبراوي',
    subtype: 'كباب / مشويات',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Haty+El+Shabrawy+Beni+Suef',
    rating: 4.0,
    reviewCount: 45,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فطاطري الحمدين',
    subtype: 'فطاطري / معجنات',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Hamdein+Feteer+Beni+Suef',
    rating: 4.2,
    reviewCount: 60,
    hours: '08:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فطاطري المدينة',
    subtype: 'فطاطري / معجنات',
    address: 'وسط البلد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Medina+Feteer+Beni+Suef',
    rating: 4.0,
    reviewCount: 35,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم الدهان',
    subtype: 'كشري / مصري',
    address: 'شارع بورسعيد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Dahan+Restaurant+Beni+Suef',
    rating: 4.1,
    reviewCount: 40,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فول وطعمية محمد أحمد',
    subtype: 'فول وطعمية',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Mohamed+Ahmed+Foul+Beni+Suef',
    rating: 4.3,
    reviewCount: 80,
    hours: '05:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم جاد',
    subtype: 'سلسلة / فول وطعمية',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '19117',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Gad+Restaurant+Beni+Suef',
    rating: 4.2,
    reviewCount: 150,
    hours: '06:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم مؤمن',
    subtype: 'سلسلة / فاست فود',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Moemen+Restaurant+Beni+Suef',
    rating: 3.9,
    reviewCount: 70,
    hours: '08:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'أسماك البحار',
    subtype: 'مأكولات بحرية',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Asmak+El+Behar+Beni+Suef',
    rating: 4.0,
    reviewCount: 38,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم 10 أبو الفرج',
    subtype: 'مصري / فاست فود',
    address: 'شارع أبو الفرج، بني سويف',
    area: 'وسط البلد',
    phone1: '01276126676',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=10+Abu+El+Farag+Beni+Suef',
    rating: 3.8,
    reviewCount: 25,
    hours: '10:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'بيتزا كينج',
    subtype: 'بيتزا / فاست فود',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Pizza+King+Beni+Suef',
    rating: 3.9,
    reviewCount: 32,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم حضرموت',
    subtype: 'يمني / مندي',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Hadramout+Restaurant+Beni+Suef',
    rating: 4.0,
    reviewCount: 28,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'تشكن فيليه',
    subtype: 'دجاج / فاست فود',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Chicken+Fillet+Beni+Suef',
    rating: 3.7,
    reviewCount: 20,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'إسكتو',
    subtype: 'مصري / فاست فود',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Eskto+Beni+Suef',
    rating: 3.8,
    reviewCount: 22,
    hours: '10:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم البركة',
    subtype: 'مصري / مشويات',
    address: 'الواسطى، بني سويف',
    area: 'الواسطى',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Baraka+Restaurant+Wasty+Beni+Suef',
    rating: 3.9,
    reviewCount: 18,
    hours: '10:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم النيل',
    subtype: 'مصري / أسماك',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Restaurant+Beni+Suef',
    rating: 3.8,
    reviewCount: 15,
    hours: '11:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كباب الحاج',
    subtype: 'كباب / مشويات',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kebab+El+Hag+Beni+Suef',
    rating: 4.1,
    reviewCount: 50,
    hours: '11:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فول الحاج محمود',
    subtype: 'فول وطعمية',
    address: 'وسط البلد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Foul+Hag+Mahmoud+Beni+Suef',
    rating: 4.2,
    reviewCount: 65,
    hours: '05:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم بلبل',
    subtype: 'مصري / كشري',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Bolbol+Restaurant+Beni+Suef',
    rating: 3.8,
    reviewCount: 22,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم أم حسن',
    subtype: 'مصري / بيتي',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Om+Hassan+Restaurant+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '10:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم الأصيل',
    subtype: 'مشويات / شرقي',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Aseel+Restaurant+Beni+Suef',
    rating: 3.9,
    reviewCount: 20,
    hours: '11:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مطعم كورنيش',
    subtype: 'مصري / نيلي',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '01022448820',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kornish+Restaurant+Beni+Suef',
    rating: 4.1,
    reviewCount: 45,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
];

// --- PHARMACIES ---
const pharmacies: MerchantData[] = [
  {
    name: 'صيدلية الإسعاف',
    subtype: 'صيدلية عامة',
    address: 'شارع صميدة متفرع من شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '01154750570',
    phone2: '0822333701',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Esaaf+Pharmacy+Beni+Suef',
    rating: 4.3,
    reviewCount: 65,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية العربي',
    subtype: 'صيدلية عامة',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Araby+Pharmacy+Beni+Suef',
    rating: 4.2,
    reviewCount: 48,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية أبو سبعة',
    subtype: 'صيدلية عامة',
    address: 'شارع عبد السلام عارف، أمام أبراج الأوقاف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Abu+Sab3a+Pharmacy+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية صبحي',
    subtype: 'صيدلية عامة',
    address: 'شارع عبد السلام عارف، ميدان الزراعيين، بني سويف',
    area: 'وسط البلد',
    phone1: '01111389993',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Sobhy+Pharmacy+Beni+Suef',
    rating: 4.1,
    reviewCount: 38,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدليات كير',
    subtype: 'سلسلة صيدليات',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '01101433102',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Care+Pharmacy+Beni+Suef',
    rating: 4.3,
    reviewCount: 55,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الحياة',
    subtype: 'صيدلية عامة',
    address: 'أمام مزلقان المديرية، ناصية شارع رجائي، بني سويف',
    area: 'وسط البلد',
    phone1: '01101444423',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Alhayah+Pharmacy+Beni+Suef',
    rating: 4.0,
    reviewCount: 42,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية أبو سيف',
    subtype: 'صيدلية عامة',
    address: 'أرض الحرية، برج الجامعة، بني سويف',
    area: 'أرض الحرية',
    phone1: '01110888411',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Abu+Seif+Pharmacy+Beni+Suef',
    rating: 4.0,
    reviewCount: 25,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية البرج',
    subtype: 'صيدلية عامة',
    address: 'برج الندى، شارع الإبراهيمية، بني سويف',
    area: 'وسط البلد',
    phone1: '01275550308',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Borg+Pharmacy+Beni+Suef',
    rating: 3.9,
    reviewCount: 20,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدليات العزبي',
    subtype: 'سلسلة صيدليات',
    address: 'شارع بورسعيد، ناصية شارع رجائي، بني سويف',
    area: 'وسط البلد',
    phone1: '19600',
    phone2: '01225035707',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Ezaby+Pharmacy+Beni+Suef',
    rating: 4.4,
    reviewCount: 180,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية زمزم',
    subtype: 'صيدلية عامة',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '01120629910',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Zamzam+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 15,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الدكتور',
    subtype: 'صيدلية عامة',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Doctor+Pharmacy+Beni+Suef',
    rating: 4.0,
    reviewCount: 22,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الشفاء',
    subtype: 'صيدلية عامة',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Shefaa+Pharmacy+Beni+Suef',
    rating: 3.9,
    reviewCount: 18,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية النيل',
    subtype: 'صيدلية عامة',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Pharmacy+Beni+Suef',
    rating: 3.7,
    reviewCount: 12,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية بني سويف الجديدة',
    subtype: 'صيدلية عامة',
    address: '6 شارع الأباصيري، بجوار معرض أبو سيفين للسيراميك، بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=New+Beni+Suef+Pharmacy',
    rating: 3.8,
    reviewCount: 14,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية طوسون',
    subtype: 'صيدلية عامة',
    address: 'شارع طوسون متفرع من شارع أحمد عرابي، بجوار مسجد السيدة حورية',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Toson+Pharmacy+Beni+Suef',
    rating: 3.6,
    reviewCount: 10,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية الدعوة',
    subtype: 'صيدلية عامة',
    address: 'شارع عبد السلام عارف، قريب من مستشفى الدعوة الإسلامية',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Daawa+Pharmacy+Beni+Suef',
    rating: 3.7,
    reviewCount: 11,
    hours: '09:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية الأمل',
    subtype: 'صيدلية عامة',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Amal+Pharmacy+Beni+Suef',
    rating: 3.5,
    reviewCount: 8,
    hours: '09:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية المعراج',
    subtype: 'صيدلية عامة',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Meraaj+Pharmacy+Beni+Suef',
    rating: 3.6,
    reviewCount: 9,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية الرحمة',
    subtype: 'صيدلية عامة',
    address: 'الواسطى، بني سويف',
    area: 'الواسطى',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Rahma+Pharmacy+Beni+Suef',
    rating: 3.5,
    reviewCount: 7,
    hours: '09:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية الفاروق',
    subtype: 'صيدلية عامة',
    address: 'شارع كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Farouk+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 16,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  // === NEW PHARMACIES (21-40) ===
  {
    name: 'صيدلية 19011',
    subtype: 'سلسلة صيدليات',
    address: 'شارع بورسعيد، تقاطع شارع رجائي، بني سويف',
    area: 'وسط البلد',
    phone1: '19011',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=19011+Pharmacy+Beni+Suef',
    rating: 4.3,
    reviewCount: 95,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية طريق الفيوم',
    subtype: 'صيدلية عامة',
    address: 'طريق الفيوم، بني سويف',
    area: 'وسط البلد',
    phone1: '01013838837',
    phone2: '01144469842',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Fayoum+Road+Pharmacy+Beni+Suef',
    rating: 4.0,
    reviewCount: 25,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية ناصر',
    subtype: 'صيدلية عامة',
    address: 'شارع جمال عبد الناصر، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nasser+Pharmacy+Beni+Suef',
    rating: 3.9,
    reviewCount: 20,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية سيف',
    subtype: 'سلسلة صيدليات',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '19199',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Seif+Pharmacy+Beni+Suef',
    rating: 4.2,
    reviewCount: 120,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية رشدي',
    subtype: 'سلسلة صيدليات',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '19014',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Roshdy+Pharmacy+Beni+Suef',
    rating: 4.1,
    reviewCount: 85,
    hours: '24 ساعة',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية المتحدة',
    subtype: 'صيدلية عامة',
    address: 'شارع بورسعيد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=United+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الإخلاص',
    subtype: 'صيدلية عامة',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ekhlas+Pharmacy+Beni+Suef',
    rating: 3.7,
    reviewCount: 14,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية الجامعة',
    subtype: 'صيدلية عامة',
    address: 'أمام جامعة بني سويف، شارع صلاح سالم',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=University+Pharmacy+Beni+Suef',
    rating: 3.9,
    reviewCount: 22,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الإيمان',
    subtype: 'صيدلية عامة',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Iman+Pharmacy+Beni+Suef',
    rating: 3.6,
    reviewCount: 11,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية التحرير',
    subtype: 'صيدلية عامة',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Tahrir+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 15,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية المستشفى العام',
    subtype: 'صيدلية مستشفى',
    address: 'أمام المستشفى العام، شارع صلاح سالم، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=General+Hospital+Pharmacy+Beni+Suef',
    rating: 3.7,
    reviewCount: 20,
    hours: '24 ساعة',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية النور',
    subtype: 'صيدلية عامة',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Nour+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 16,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الحكمة',
    subtype: 'صيدلية عامة',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Hekma+Pharmacy+Beni+Suef',
    rating: 3.6,
    reviewCount: 10,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية السلام',
    subtype: 'صيدلية عامة',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Salam+Pharmacy+Beni+Suef',
    rating: 3.7,
    reviewCount: 12,
    hours: '09:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية أولاد المعلم',
    subtype: 'صيدلية عامة',
    address: 'شارع الإبراهيمية، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Awlad+El+Moalem+Pharmacy+Beni+Suef',
    rating: 3.9,
    reviewCount: 18,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية الأندلس',
    subtype: 'صيدلية عامة',
    address: 'شرق النيل، بجوار مبنى المحافظة، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Andalus+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 14,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية بسمة',
    subtype: 'صيدلية عامة',
    address: 'أرض الحرية، بجوار كنتاكي، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Basma+Pharmacy+Beni+Suef',
    rating: 3.7,
    reviewCount: 11,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية الواسطى المركزية',
    subtype: 'صيدلية عامة',
    address: 'شارع الجمهورية، الواسطى، بني سويف',
    area: 'الواسطى',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Wasty+Central+Pharmacy+Beni+Suef',
    rating: 3.6,
    reviewCount: 9,
    hours: '08:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'صيدلية كورنيش النيل',
    subtype: 'صيدلية عامة',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kornish+Nile+Pharmacy+Beni+Suef',
    rating: 3.9,
    reviewCount: 17,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'صيدلية المنار',
    subtype: 'صيدلية عامة',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Manar+Pharmacy+Beni+Suef',
    rating: 3.8,
    reviewCount: 13,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
];

// --- SUPERMARKETS ---
const supermarkets: MerchantData[] = [
  {
    name: 'هايبر ماركت الخديوي',
    subtype: 'هايبر ماركت',
    address: 'تقاطع الثانوية العسكرية، شارع الروضة، برج الخديوي، بني سويف',
    area: 'وسط البلد',
    phone1: '01100099333',
    phone2: '01003316735',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Al+Khediwe+Hyper+Market+Beni+Suef',
    rating: 4.2,
    reviewCount: 85,
    hours: '08:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'أولاد رجب',
    subtype: 'هايبر ماركت',
    address: 'قسم بني سويف، بني سويف',
    area: 'وسط البلد',
    phone1: '01013238881',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Awlad+Ragab+Beni+Suef',
    rating: 4.5,
    reviewCount: 220,
    hours: '07:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'خيرات ماركت',
    subtype: 'سوبر ماركت',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kheirat+Market+Beni+Suef',
    rating: 4.0,
    reviewCount: 35,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت الصفوة',
    subtype: 'سوبر ماركت',
    address: 'محافظة بني سويف',
    area: 'وسط البلد',
    phone1: '0822117203',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Safwa+Supermarket+Beni+Suef',
    rating: 4.1,
    reviewCount: 45,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'الراية ماركت',
    subtype: 'سوبر ماركت',
    address: 'ميدان المديرية، بجوار عمر أفندي، أمام الصالون الأخضر، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Raya+Market+Beni+Suef',
    rating: 3.9,
    reviewCount: 28,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت الملاح',
    subtype: 'سوبر ماركت',
    address: 'الجزيرة المرتفعة، أمام مدرسة الجزيرة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Mallah+Supermarket+Beni+Suef',
    rating: 3.7,
    reviewCount: 15,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'ماركت الحرية',
    subtype: 'ميني ماركت',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Horreya+Market+Beni+Suef',
    rating: 3.8,
    reviewCount: 12,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت النيل',
    subtype: 'سوبر ماركت',
    address: 'شرق النيل، خلف مبنى محافظة بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Supermarket+Beni+Suef',
    rating: 3.6,
    reviewCount: 10,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'ماركت الجامعة',
    subtype: 'ميني ماركت',
    address: 'شارع صلاح سالم، أمام كلية التربية، جامعة بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=University+Market+Beni+Suef',
    rating: 3.5,
    reviewCount: 8,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'ب لبن',
    subtype: 'منتجات ألبان / ميني ماركت',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=B+Laban+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت الكورنيش',
    subtype: 'سوبر ماركت',
    address: 'شارع كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kornish+Supermarket+Beni+Suef',
    rating: 3.7,
    reviewCount: 14,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'هايبر كمال محمد',
    subtype: 'هايبر ماركت',
    address: 'شارع كمال محمد متفرع من شارع الروضة، بجوار مدرسة الحرية',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kamal+Mohamed+Hyper+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'ماركت سليمان',
    subtype: 'سوبر ماركت',
    address: 'شارع المهندس سليمان متولي متفرع من شارع كورنيش النيل',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Soliman+Market+Beni+Suef',
    rating: 3.5,
    reviewCount: 9,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'ماركت مدخل المدينة',
    subtype: 'ميني ماركت',
    address: 'شارع مدخل المدينة، شرق النيل، خلف مبنى المحافظة',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=City+Entrance+Market+Beni+Suef',
    rating: 3.4,
    reviewCount: 6,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'التوحيد والنور',
    subtype: 'هايبر ماركت',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Tawheed+wel+Nour+Beni+Suef',
    rating: 4.3,
    reviewCount: 150,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  // === NEW SUPERMARKETS (16-30) ===
  {
    name: 'سوبر ماركت أحمد حسن',
    subtype: 'سوبر ماركت',
    address: 'شارع الجبالي، بني سويف',
    area: 'وسط البلد',
    phone1: '0822332239',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ahmed+Hassan+Supermarket+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '07:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'مصرية ماركت',
    subtype: 'سوبر ماركت',
    address: 'شارع صلاح سالم، أمام كلية التربية، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Masreya+Market+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'الصعيدي ماركت',
    subtype: 'سوبر ماركت',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '01201268008',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Saeedy+Market+Beni+Suef',
    rating: 3.9,
    reviewCount: 22,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'أولاد رجب - أرض الحرية',
    subtype: 'هايبر ماركت',
    address: 'أرض الحرية، بجوار كنتاكي، بني سويف',
    area: 'أرض الحرية',
    phone1: '19225',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Awlad+Ragab+Ard+Horeya+Beni+Suef',
    rating: 4.4,
    reviewCount: 180,
    hours: '07:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كازيون - بني سويف الجديدة',
    subtype: 'سلسلة ديسكاونت',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kazyon+New+Beni+Suef',
    rating: 4.0,
    reviewCount: 45,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كازيون - وسط البلد',
    subtype: 'سلسلة ديسكاونت',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kazyon+Downtown+Beni+Suef',
    rating: 4.1,
    reviewCount: 55,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كازيون - شرق النيل',
    subtype: 'سلسلة ديسكاونت',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kazyon+East+Nile+Beni+Suef',
    rating: 4.0,
    reviewCount: 38,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'هايبر وان',
    subtype: 'هايبر ماركت',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Hyper+One+Beni+Suef',
    rating: 4.0,
    reviewCount: 35,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'ميني ماركت الزهور',
    subtype: 'ميني ماركت',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Zohour+Mini+Market+Beni+Suef',
    rating: 3.6,
    reviewCount: 10,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت البركة',
    subtype: 'سوبر ماركت',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Baraka+Supermarket+Beni+Suef',
    rating: 3.7,
    reviewCount: 12,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت الأمين',
    subtype: 'سوبر ماركت',
    address: 'شارع بورسعيد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Amin+Supermarket+Beni+Suef',
    rating: 3.8,
    reviewCount: 15,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'ماركت الواسطى المركزي',
    subtype: 'سوبر ماركت',
    address: 'شارع الجمهورية، الواسطى، بني سويف',
    area: 'الواسطى',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Wasty+Central+Market+Beni+Suef',
    rating: 3.6,
    reviewCount: 8,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت الوفاء',
    subtype: 'سوبر ماركت',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Wafaa+Supermarket+Beni+Suef',
    rating: 3.7,
    reviewCount: 11,
    hours: '07:00 ص - 12:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'ماركت الإبراهيمية',
    subtype: 'ميني ماركت',
    address: 'شارع الإبراهيمية، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ibrahimia+Market+Beni+Suef',
    rating: 3.5,
    reviewCount: 7,
    hours: '07:00 ص - 11:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوبر ماركت الجامعة الحديث',
    subtype: 'سوبر ماركت',
    address: 'أمام جامعة بني سويف، شارع صلاح سالم',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Modern+University+Supermarket+Beni+Suef',
    rating: 3.8,
    reviewCount: 16,
    hours: '07:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
];

// --- SWEETS & CAFES ---
const sweetsCafes: MerchantData[] = [
  {
    name: 'مطعم الحلواني',
    subtype: 'حلويات / معجنات',
    address: 'أبو الفرج، قسم بني سويف، محافظة بني سويف',
    area: 'وسط البلد',
    phone1: '0822342828',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Al+Halawani+Beni+Suef',
    rating: 4.4,
    reviewCount: 120,
    hours: '08:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'حلواني اللبناني',
    subtype: 'حلويات شرقية / غربية',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '@ellebnany.pastries',
    googleMaps: 'https://maps.google.com/?q=Lebanese+Pastry+Beni+Suef',
    rating: 4.3,
    reviewCount: 85,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'حلواني الصردي',
    subtype: 'حلويات شرقية',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Sardy+Pastry+Beni+Suef',
    rating: 4.2,
    reviewCount: 70,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سيليو كافيه',
    subtype: 'كافيه / آيس كريم',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Celio+Cafe+Beni+Suef',
    rating: 4.1,
    reviewCount: 45,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'استكانة كافيه',
    subtype: 'كافيه',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Estekana+Cafe+Beni+Suef',
    rating: 4.0,
    reviewCount: 38,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلواني العبد',
    subtype: 'سلسلة حلويات',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '17111',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=El+Abd+Pastry+Beni+Suef',
    rating: 4.5,
    reviewCount: 200,
    hours: '09:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'جراج لاونج كافيه',
    subtype: 'كافيه / لاونج',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Garage+Lounge+Cafe+Beni+Suef',
    rating: 4.0,
    reviewCount: 25,
    hours: '12:00 م - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كوفي بريك',
    subtype: 'كافيه / قهوة',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Coffee+Break+Beni+Suef',
    rating: 3.9,
    reviewCount: 22,
    hours: '08:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'نيو كوب مارينا كافيه',
    subtype: 'كافيه / نيلي',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=New+Cop+Marina+Cafe+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كافيه شرق النيل',
    subtype: 'كافيه',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=East+Nile+Cafe+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلويات سعد الدين',
    subtype: 'حلويات شرقية / غربية',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Saadeddin+Pastry+Beni+Suef',
    rating: 4.2,
    reviewCount: 55,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كافيه الكورنيش',
    subtype: 'كافيه / مشروبات',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kornish+Cafe+Beni+Suef',
    rating: 3.7,
    reviewCount: 15,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كريب ستيشن',
    subtype: 'كريب / حلويات',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Crepe+Station+Beni+Suef',
    rating: 3.8,
    reviewCount: 20,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كافيه بني سويف الجديدة',
    subtype: 'كافيه',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=New+Beni+Suef+Cafe',
    rating: 3.6,
    reviewCount: 10,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلواني الزهور',
    subtype: 'حلويات',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Zohour+Pastry+Beni+Suef',
    rating: 3.7,
    reviewCount: 12,
    hours: '09:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  // === NEW SWEETS & CAFES (16-30) ===
  {
    name: 'لاباتيسري',
    subtype: 'حلويات فرنسية',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=La+Patisserie+Beni+Suef',
    rating: 4.2,
    reviewCount: 45,
    hours: '09:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'عصير تايم',
    subtype: 'عصائر / سموثي',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Juice+Time+Beni+Suef',
    rating: 4.0,
    reviewCount: 30,
    hours: '08:00 ص - 02:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'بوبز كافيه',
    subtype: 'كافيه / مشروبات',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Bobs+Cafe+Beni+Suef',
    rating: 4.1,
    reviewCount: 35,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلواني السلطان',
    subtype: 'حلويات شرقية',
    address: 'شارع بورسعيد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Sultan+Pastry+Beni+Suef',
    rating: 4.0,
    reviewCount: 40,
    hours: '08:00 ص - 12:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كافيه ذا لاونج',
    subtype: 'كافيه / لاونج',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=The+Lounge+Cafe+Beni+Suef',
    rating: 4.0,
    reviewCount: 28,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلواني المدينة',
    subtype: 'حلويات شرقية / غربية',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Medina+Pastry+Beni+Suef',
    rating: 3.9,
    reviewCount: 22,
    hours: '08:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كافيه أرض الحرية',
    subtype: 'كافيه',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ard+Horreya+Cafe+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلويات الفيروز',
    subtype: 'حلويات شرقية',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Fairouz+Sweets+Beni+Suef',
    rating: 3.8,
    reviewCount: 15,
    hours: '08:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'ستار باكس كافيه',
    subtype: 'كافيه / قهوة مختصة',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Star+Bucks+Cafe+Beni+Suef',
    rating: 3.9,
    reviewCount: 20,
    hours: '08:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلواني الواسطى',
    subtype: 'حلويات',
    address: 'الواسطى، بني سويف',
    area: 'الواسطى',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Wasty+Pastry+Beni+Suef',
    rating: 3.6,
    reviewCount: 10,
    hours: '08:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'كافيه دريم',
    subtype: 'كافيه / آيس كريم',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Dream+Cafe+Beni+Suef',
    rating: 3.7,
    reviewCount: 14,
    hours: '10:00 ص - 01:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'عصائر الربيع',
    subtype: 'عصائر طبيعية',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Rabee+Juice+Beni+Suef',
    rating: 4.1,
    reviewCount: 35,
    hours: '07:00 ص - 01:00 ص',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'حلواني النيل',
    subtype: 'حلويات',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Pastry+Beni+Suef',
    rating: 3.7,
    reviewCount: 13,
    hours: '08:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'كافيه الإبراهيمية',
    subtype: 'كافيه / شيشة',
    address: 'شارع الإبراهيمية، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ibrahimia+Cafe+Beni+Suef',
    rating: 3.6,
    reviewCount: 11,
    hours: '10:00 ص - 02:00 ص',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'حلواني الأمير',
    subtype: 'حلويات شرقية / تورت',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Amir+Pastry+Beni+Suef',
    rating: 3.8,
    reviewCount: 16,
    hours: '08:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
];

// --- VEGETABLES & FRUITS ---
const vegFruits: MerchantData[] = [
  {
    name: 'سوق الخضار المركزي',
    subtype: 'سوق خضار',
    address: 'وسط البلد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Central+Vegetable+Market+Beni+Suef',
    rating: 4.0,
    reviewCount: 45,
    hours: '06:00 ص - 06:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوق الفواكه بني سويف',
    subtype: 'سوق فواكه',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Fruit+Market+Beni+Suef',
    rating: 3.9,
    reviewCount: 30,
    hours: '06:00 ص - 08:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه الأمل',
    subtype: 'محل خضار وفواكه',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Amal+Vegetables+Beni+Suef',
    rating: 3.8,
    reviewCount: 18,
    hours: '06:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سوق شرق النيل',
    subtype: 'سوق شعبي',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=East+Nile+Market+Beni+Suef',
    rating: 3.7,
    reviewCount: 22,
    hours: '06:00 ص - 06:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار الحرية',
    subtype: 'محل خضار',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Horreya+Vegetables+Beni+Suef',
    rating: 3.6,
    reviewCount: 12,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'فواكه النيل',
    subtype: 'محل فواكه',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Fruits+Beni+Suef',
    rating: 3.5,
    reviewCount: 10,
    hours: '07:00 ص - 10:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوق الواسطى',
    subtype: 'سوق شعبي',
    address: 'الواسطى، بني سويف',
    area: 'الواسطى',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Wasty+Market+Beni+Suef',
    rating: 3.8,
    reviewCount: 25,
    hours: '06:00 ص - 06:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار بني سويف الجديدة',
    subtype: 'محل خضار',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=New+Beni+Suef+Vegetables',
    rating: 3.5,
    reviewCount: 8,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فواكه المنشاوي',
    subtype: 'محل فواكه',
    address: 'بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Menshawi+Fruits+Beni+Suef',
    rating: 4.0,
    reviewCount: 20,
    hours: '07:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سوق الزهور',
    subtype: 'سوق شعبي',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Zohour+Market+Beni+Suef',
    rating: 3.6,
    reviewCount: 14,
    hours: '06:00 ص - 07:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه الروضة',
    subtype: 'محل خضار وفواكه',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Rawda+Vegetables+Beni+Suef',
    rating: 3.7,
    reviewCount: 11,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'محل فواكه الجامعة',
    subtype: 'محل فواكه',
    address: 'أمام جامعة بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=University+Fruits+Beni+Suef',
    rating: 3.8,
    reviewCount: 16,
    hours: '07:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'خضار الكورنيش',
    subtype: 'محل خضار',
    address: 'شارع كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kornish+Vegetables+Beni+Suef',
    rating: 3.4,
    reviewCount: 7,
    hours: '06:00 ص - 08:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه الإبراهيمية',
    subtype: 'محل خضار وفواكه',
    address: 'شارع الإبراهيمية، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ibrahimia+Vegetables+Beni+Suef',
    rating: 3.5,
    reviewCount: 9,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوق الثلاثاء',
    subtype: 'سوق أسبوعي',
    address: 'وسط البلد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Tuesday+Market+Beni+Suef',
    rating: 4.1,
    reviewCount: 55,
    hours: 'الثلاثاء فقط 06:00 ص - 04:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  // === NEW VEGETABLES & FRUITS (16-30) ===
  {
    name: 'سوق الجمعة',
    subtype: 'سوق أسبوعي',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Friday+Market+Beni+Suef',
    rating: 4.0,
    reviewCount: 40,
    hours: 'الجمعة فقط 06:00 ص - 02:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه السيد',
    subtype: 'محل خضار وفواكه',
    address: 'شارع بورسعيد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Sayed+Vegetables+Beni+Suef',
    rating: 3.9,
    reviewCount: 18,
    hours: '06:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فواكه الموسم',
    subtype: 'محل فواكه',
    address: 'شارع عبد السلام عارف، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Season+Fruits+Beni+Suef',
    rating: 3.8,
    reviewCount: 15,
    hours: '07:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'خضار الجامعة',
    subtype: 'محل خضار',
    address: 'أمام جامعة بني سويف، شارع صلاح سالم',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=University+Vegetables+Beni+Suef',
    rating: 3.7,
    reviewCount: 12,
    hours: '06:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'سوق أرض الحرية',
    subtype: 'سوق شعبي',
    address: 'أرض الحرية، بني سويف',
    area: 'أرض الحرية',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Ard+Horreya+Market+Beni+Suef',
    rating: 3.8,
    reviewCount: 20,
    hours: '06:00 ص - 06:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه الخير',
    subtype: 'محل خضار وفواكه',
    address: 'شارع أحمد عرابي، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Kheir+Vegetables+Beni+Suef',
    rating: 4.0,
    reviewCount: 25,
    hours: '06:00 ص - 11:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فواكه الصعيد',
    subtype: 'محل فواكه',
    address: 'شرق النيل، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Saeed+Fruits+Beni+Suef',
    rating: 3.7,
    reviewCount: 14,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار البركة',
    subtype: 'محل خضار',
    address: 'شارع الروضة، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Baraka+Vegetables+Beni+Suef',
    rating: 3.6,
    reviewCount: 10,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوق بني سويف الجديدة المركزي',
    subtype: 'سوق شعبي',
    address: 'بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=New+Beni+Suef+Central+Market',
    rating: 3.8,
    reviewCount: 18,
    hours: '06:00 ص - 06:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه النيل',
    subtype: 'محل خضار وفواكه',
    address: 'كورنيش النيل، بني سويف',
    area: 'كورنيش النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Nile+Vegetables+Fruits+Beni+Suef',
    rating: 3.5,
    reviewCount: 8,
    hours: '06:00 ص - 08:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'فواكه الأمين',
    subtype: 'محل فواكه',
    address: 'شارع بورسعيد، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Amin+Fruits+Beni+Suef',
    rating: 3.9,
    reviewCount: 16,
    hours: '07:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'خضار الصحة',
    subtype: 'محل خضار',
    address: 'حي الزهور، بني سويف',
    area: 'حي الزهور',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Health+Vegetables+Beni+Suef',
    rating: 3.6,
    reviewCount: 9,
    hours: '06:00 ص - 08:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'سوق الحسينية',
    subtype: 'سوق شعبي',
    address: 'شارع الحسينية، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Husseinia+Market+Beni+Suef',
    rating: 3.9,
    reviewCount: 22,
    hours: '05:00 ص - 06:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
  {
    name: 'خضار وفواكه المحطة',
    subtype: 'محل خضار وفواكه',
    address: 'بجوار محطة القطار، بني سويف',
    area: 'وسط البلد',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=Station+Vegetables+Beni+Suef',
    rating: 3.7,
    reviewCount: 13,
    hours: '05:00 ص - 10:00 م',
    hasDelivery: 'نعم',
    status: 'نشط',
  },
  {
    name: 'فواكه شرق النيل',
    subtype: 'محل فواكه',
    address: 'شرق النيل، بجوار التوحيد والنور، بني سويف',
    area: 'شرق النيل',
    phone1: '',
    phone2: '',
    facebook: '',
    instagram: '',
    googleMaps: 'https://maps.google.com/?q=East+Nile+Fruits+Beni+Suef',
    rating: 3.6,
    reviewCount: 11,
    hours: '06:00 ص - 09:00 م',
    hasDelivery: 'لا',
    status: 'نشط',
  },
];

// ============================================================
// GOOGLE SHEETS API FUNCTIONS
// ============================================================

async function getAuth(): Promise<JWT> {
  // Try environment variable first
  const keyEnv = process.env.GOOGLE_SERVICE_ACCOUNT_KEY;
  if (keyEnv) {
    const keyData = JSON.parse(keyEnv);
    return new JWT({
      email: keyData.client_email,
      key: keyData.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
  }

  // Try file-based credentials
  const credPaths = [
    path.join(__dirname, '..', 'credentials', 'service-account.json'),
    path.join(__dirname, '..', 'service-account.json'),
    process.env.GOOGLE_APPLICATION_CREDENTIALS || '',
  ].filter(Boolean);

  for (const p of credPaths) {
    if (fs.existsSync(p)) {
      const keyData = JSON.parse(fs.readFileSync(p, 'utf8'));
      return new JWT({
        email: keyData.client_email,
        key: keyData.private_key,
        scopes: ['https://www.googleapis.com/auth/spreadsheets'],
      });
    }
  }

  throw new Error(
    'No Google credentials found. Set GOOGLE_SERVICE_ACCOUNT_KEY env var ' +
      'or place service-account.json in ./credentials/ directory.\n' +
      'The service account must have the Google Sheet shared with its email address.'
  );
}

async function setupSheets(sheets: sheets_v4.Sheets): Promise<void> {
  console.log('📋 Getting existing sheets...');

  const spreadsheet = await sheets.spreadsheets.get({
    spreadsheetId: SPREADSHEET_ID,
    fields: 'sheets.properties',
  });

  const existingSheets = spreadsheet.data.sheets?.map((s) => s.properties?.title) || [];
  console.log(`   Found ${existingSheets.length} existing sheets: ${existingSheets.join(', ')}`);

  const allSheetNames = [...CATEGORY_SHEETS.map((s) => s.title), ...MANAGEMENT_SHEETS];

  const sheetsToCreate = allSheetNames.filter((name) => !existingSheets.includes(name));

  if (sheetsToCreate.length > 0) {
    console.log(`   Creating ${sheetsToCreate.length} new sheets...`);
    const requests: sheets_v4.Schema$Request[] = sheetsToCreate.map((title) => ({
      addSheet: {
        properties: { title },
      },
    }));

    await sheets.spreadsheets.batchUpdate({
      spreadsheetId: SPREADSHEET_ID,
      requestBody: { requests },
    });
    console.log('   ✅ Sheets created successfully');
  } else {
    console.log('   ✅ All sheets already exist');
  }
}

function merchantToRow(index: number, m: MerchantData): string[] {
  const { priority, wave } = classifyPriority(m.rating, m.reviewCount);
  return [
    String(index + 1),
    m.name,
    m.subtype,
    m.address,
    m.area,
    m.phone1,
    m.phone2,
    m.facebook,
    m.instagram,
    m.googleMaps,
    String(m.rating || ''),
    String(m.reviewCount || ''),
    m.hours,
    m.hasDelivery,
    m.status,
    priority,
    wave,
    'لم يتم التواصل',
    '',
    '',
    '',
    '',
    'لا',
    '',
    today,
  ];
}

async function writeCategorySheet(
  sheets: sheets_v4.Sheets,
  sheetTitle: string,
  category: string,
  merchants: MerchantData[]
): Promise<void> {
  console.log(`\n📝 Writing ${sheetTitle} (${merchants.length} merchants)...`);

  // Row 1: Title
  const titleRow = [`قاعدة بيانات ${category} - بني سويف - إنجزنا`];

  // Row 2: Summary
  const high = merchants.filter(
    (m) => classifyPriority(m.rating, m.reviewCount).priority === 'أولوية عالية'
  ).length;
  const med = merchants.filter(
    (m) => classifyPriority(m.rating, m.reviewCount).priority === 'أولوية متوسطة'
  ).length;
  const low = merchants.filter(
    (m) => classifyPriority(m.rating, m.reviewCount).priority === 'أولوية منخفضة'
  ).length;
  const summaryRow = [
    `إجمالي: ${merchants.length} | أولوية عالية: ${high} | أولوية متوسطة: ${med} | أولوية منخفضة: ${low} | الهدف: 60 | تاريخ التحديث: ${today}`,
  ];

  // Row 3: Headers
  // Row 4+: Data
  const dataRows = merchants.map((m, i) => merchantToRow(i, m));

  const allRows = [titleRow, summaryRow, HEADERS, ...dataRows];

  await sheets.spreadsheets.values.update({
    spreadsheetId: SPREADSHEET_ID,
    range: `'${sheetTitle}'!A1`,
    valueInputOption: 'RAW',
    requestBody: { values: allRows },
  });

  console.log(`   ✅ ${merchants.length} merchants written to ${sheetTitle}`);
}

async function writeDashboard(sheets: sheets_v4.Sheets): Promise<void> {
  console.log('\n📊 Writing Dashboard (لوحة التحكم)...');

  const allCategories = [
    { name: '🍔 مطاعم', data: restaurants },
    { name: '💊 صيدليات', data: pharmacies },
    { name: '🛒 سوبر ماركت', data: supermarkets },
    { name: '🍰 حلويات وكافيهات', data: sweetsCafes },
    { name: '🥬 خضار وفواكه', data: vegFruits },
  ];

  const totalMerchants = allCategories.reduce((sum, c) => sum + c.data.length, 0);
  const targetPerCategory = 60;
  const totalTarget = targetPerCategory * allCategories.length;

  const dashboardRows: string[][] = [
    ['📊 لوحة التحكم - قاعدة بيانات المتاجر - إنجزنا بني سويف'],
    [`آخر تحديث: ${today} | إجمالي المتاجر: ${totalMerchants} | الهدف: ${totalTarget}`],
    [],
    ['═══════════════════════════════════════════════════════════════'],
    ['📈 ملخص عام'],
    ['═══════════════════════════════════════════════════════════════'],
    [],
    ['المؤشر', 'القيمة'],
    ['إجمالي المتاجر المسجلة', String(totalMerchants)],
    ['الهدف الكلي', String(totalTarget)],
    ['نسبة الإنجاز', `${Math.round((totalMerchants / totalTarget) * 100)}%`],
    ['المتبقي للهدف', String(Math.max(0, totalTarget - totalMerchants))],
    [],
    ['═══════════════════════════════════════════════════════════════'],
    ['📊 تفاصيل حسب الفئة'],
    ['═══════════════════════════════════════════════════════════════'],
    [],
    [
      'الفئة',
      'العدد',
      'الهدف',
      'النسبة',
      'أولوية عالية',
      'أولوية متوسطة',
      'أولوية منخفضة',
      'موجة 1',
      'موجة 2',
      'موجة 3',
    ],
  ];

  let totalHigh = 0,
    totalMed = 0,
    totalLow = 0;
  let totalW1 = 0,
    totalW2 = 0,
    totalW3 = 0;

  for (const cat of allCategories) {
    const high = cat.data.filter(
      (m) => classifyPriority(m.rating, m.reviewCount).wave === 'موجة 1'
    ).length;
    const med = cat.data.filter(
      (m) => classifyPriority(m.rating, m.reviewCount).wave === 'موجة 2'
    ).length;
    const low = cat.data.filter(
      (m) => classifyPriority(m.rating, m.reviewCount).wave === 'موجة 3'
    ).length;
    totalHigh += high;
    totalMed += med;
    totalLow += low;
    totalW1 += high;
    totalW2 += med;
    totalW3 += low;

    dashboardRows.push([
      cat.name,
      String(cat.data.length),
      String(targetPerCategory),
      `${Math.round((cat.data.length / targetPerCategory) * 100)}%`,
      String(high),
      String(med),
      String(low),
      String(high),
      String(med),
      String(low),
    ]);
  }

  dashboardRows.push([
    'الإجمالي',
    String(totalMerchants),
    String(totalTarget),
    `${Math.round((totalMerchants / totalTarget) * 100)}%`,
    String(totalHigh),
    String(totalMed),
    String(totalLow),
    String(totalW1),
    String(totalW2),
    String(totalW3),
  ]);

  dashboardRows.push(
    [],
    ['═══════════════════════════════════════════════════════════════'],
    ['📞 حالة التواصل'],
    ['═══════════════════════════════════════════════════════════════'],
    [],
    ['الحالة', 'العدد', 'النسبة'],
    ['لم يتم التواصل', String(totalMerchants), '100%'],
    ['تم التواصل - مهتم', '0', '0%'],
    ['تم التواصل - غير مهتم', '0', '0%'],
    ['تم التواصل - متابعة', '0', '0%'],
    ['تم التسجيل', '0', '0%'],
    [],
    ['═══════════════════════════════════════════════════════════════'],
    ['🎯 خطة الموجات'],
    ['═══════════════════════════════════════════════════════════════'],
    [],
    ['الموجة', 'المعيار', 'العدد', 'الحالة'],
    ['موجة 1', 'تقييم ≥ 4.0 و تقييمات ≥ 20', String(totalW1), 'جاهز للبدء'],
    ['موجة 2', 'تقييم ≥ 3.5 أو تقييمات ≥ 10', String(totalW2), 'في الانتظار'],
    ['موجة 3', 'باقي المتاجر', String(totalW3), 'في الانتظار']
  );

  await sheets.spreadsheets.values.update({
    spreadsheetId: SPREADSHEET_ID,
    range: "'📊 لوحة التحكم'!A1",
    valueInputOption: 'RAW',
    requestBody: { values: dashboardRows },
  });

  console.log('   ✅ Dashboard written successfully');
}

async function writePerformanceSheet(sheets: sheets_v4.Sheets): Promise<void> {
  console.log('\n📈 Writing Performance Tracking (متابعة الأداء)...');

  const rows: string[][] = [
    ['📈 متابعة الأداء - إنجزنا بني سويف'],
    [`تاريخ الإنشاء: ${today}`],
    [],
    ['التاريخ', 'مكالمات اليوم', 'مهتم', 'غير مهتم', 'متابعة', 'تسجيل جديد', 'المندوب', 'ملاحظات'],
    [today, '0', '0', '0', '0', '0', '', 'بداية المشروع'],
  ];

  await sheets.spreadsheets.values.update({
    spreadsheetId: SPREADSHEET_ID,
    range: "'📈 متابعة الأداء'!A1",
    valueInputOption: 'RAW',
    requestBody: { values: rows },
  });

  console.log('   ✅ Performance sheet written');
}

async function writeCRMSheet(sheets: sheets_v4.Sheets): Promise<void> {
  console.log('\n📊 Writing CRM sheet...');

  const rows: string[][] = [
    ['📊 CRM - متابعة العملاء المحتملين - إنجزنا بني سويف'],
    [`تاريخ الإنشاء: ${today}`],
    [],
    [
      '#',
      'اسم المتجر',
      'الفئة',
      'المنطقة',
      'جهة الاتصال',
      'رقم الهاتف',
      'تاريخ أول تواصل',
      'تاريخ آخر تواصل',
      'عدد المحاولات',
      'حالة التواصل',
      'نتيجة التواصل',
      'المندوب',
      'تاريخ المتابعة القادمة',
      'ملاحظات',
      'تم التسجيل؟',
    ],
  ];

  await sheets.spreadsheets.values.update({
    spreadsheetId: SPREADSHEET_ID,
    range: "'📊 CRM'!A1",
    valueInputOption: 'RAW',
    requestBody: { values: rows },
  });

  console.log('   ✅ CRM sheet written');
}

// ============================================================
// MAIN EXECUTION
// ============================================================

async function main(): Promise<void> {
  console.log('🚀 Engezna Merchant Database Setup');
  console.log('===================================\n');
  console.log(`📄 Spreadsheet ID: ${SPREADSHEET_ID}`);
  console.log(`📅 Date: ${today}\n`);

  // Authenticate
  console.log('🔑 Authenticating...');
  const auth = await getAuth();
  const sheetsApi = google.sheets({ version: 'v4', auth });

  // Phase 1: Setup sheet structure
  console.log('\n═══ PHASE 1: Setup Sheet Structure ═══');
  await setupSheets(sheetsApi);

  // Phase 2 & 3: Write merchant data with prioritization
  console.log('\n═══ PHASE 2 & 3: Write Merchant Data with Priorities ═══');

  const categoryData: { sheet: (typeof CATEGORY_SHEETS)[0]; merchants: MerchantData[] }[] = [
    { sheet: CATEGORY_SHEETS[0], merchants: restaurants },
    { sheet: CATEGORY_SHEETS[1], merchants: pharmacies },
    { sheet: CATEGORY_SHEETS[2], merchants: supermarkets },
    { sheet: CATEGORY_SHEETS[3], merchants: sweetsCafes },
    { sheet: CATEGORY_SHEETS[4], merchants: vegFruits },
  ];

  for (const { sheet, merchants } of categoryData) {
    await writeCategorySheet(sheetsApi, sheet.title, sheet.category, merchants);
    // Rate limit to avoid API quota issues
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }

  // Phase 4: Dashboard
  console.log('\n═══ PHASE 4: Dashboard & Management Sheets ═══');
  await writeDashboard(sheetsApi);
  await writePerformanceSheet(sheetsApi);
  await writeCRMSheet(sheetsApi);

  // Summary
  const total =
    restaurants.length +
    pharmacies.length +
    supermarkets.length +
    sweetsCafes.length +
    vegFruits.length;
  console.log('\n═══════════════════════════════════════');
  console.log('✅ SETUP COMPLETE');
  console.log('═══════════════════════════════════════');
  console.log(`📊 Total merchants: ${total}`);
  console.log(`   🍔 مطاعم: ${restaurants.length}`);
  console.log(`   💊 صيدليات: ${pharmacies.length}`);
  console.log(`   🛒 سوبر ماركت: ${supermarkets.length}`);
  console.log(`   🍰 حلويات وكافيهات: ${sweetsCafes.length}`);
  console.log(`   🥬 خضار وفواكه: ${vegFruits.length}`);
  console.log(`\n🔗 Open: https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}`);
}

main().catch((err) => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
